#!/usr/bin/env expect

foreach command $argv {
    spawn $command
    array set commands_by_spawn_ids [list $spawn_id $command]
}

set message_id ''
set message ''

expect {
  -i [array names commands_by_spawn_ids]
  -re "send (from .* to .*): (.*\n)" {
    set message_id $expect_out(1,string)
    set message $expect_out(2,string)
    exp_continue
  }
  -re "receive (.*)\n" {
    send $message
    exp_continue
  }
}
